services:
  hh-bot:
    build: .
    container_name: hh-bot
    restart: unless-stopped
    ipc: host
    env_file:
      - .env
    networks:
      - homelab_network
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./resumes:/app/resumes
      - ./applied.db:/app/applied.db  
      - ./state.json:/app/state.json:ro

networks:
  homelab_network:
    external: true
    name: homelab_default 
