services:
  hh-bot:
    build: .
    container_name: hh-bot
    restart: unless-stopped
    ipc: host
    env_file:
      - .env
    environment:
      - HTTP_PROXY=http://gluetun:8888
      - HTTPS_PROXY=http://gluetun:8888
      - NO_PROXY=api.hh.ru,hh.ru
      - DEBUG=pw:api
    networks:
      - homelab_network
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./resumes:/app/resumes:ro
      - ./applied.json:/app/applied.json
      - ./state.json:/app/state.json:ro # Injected session state

networks:
  homelab_network:
    external: true
    name: homelab_default 
